---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: vaultwarden-pvc
  namespace: my-vaultwarden
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 200Mi
