hostname: rancher.x.x.x.x.sslip.io # changed by me

ingress:
  # If set to false, ingress will not be created
  # Defaults to true
  # options: true, false
  enabled: false

bootstrapPassword: "ThisShouldBeSecureEnoght!"
tls: external
